# Generated by Django 3.0.1 on 2019-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191225_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='appointment_time',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
