# Generated by Django 3.0.1 on 2019-12-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20191225_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='modifiedAt',
        ),
        migrations.AlterField(
            model_name='customer',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='appointment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
