# Generated by Django 3.0.1 on 2019-12-25 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20191225_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='appointment_date_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Appointment At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
