# Generated by Django 3.0.1 on 2019-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20191225_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='appointment_date_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Appointment At'),
        ),
    ]
