# Generated by Django 3.0.1 on 2019-12-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_customer_appointment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='modifiedAt',
        ),
    ]
